version: '3'
services:
  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    image: eurobot_av_client
    container_name: eurobot_client
    ports:
      - '80:3000'
    depends_on:
      - server

  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    image: eurobot_av_server
    container_name: eurobot_server
    ports:
      - '3001:3001'
    environment:
      - DB_CONNECTION_STRING=mongodb://mongodb:27017/EurobotDB
      - CLIENT_URL=http://192.168.0.10
      - JTW_SECRET_KEY=your-secret-key
    depends_on:
      - mongodb
    networks:
      - mynetwork

  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - mynetwork

networks:
  mynetwork:
