version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: eurobot_av_client
    container_name: eurobot_client
    ports:
      - '3000:3000'
    depends_on:
      - server

  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    image: eurobot_av_server
    container_name: eurobot_server
    ports:
      - '3001:3001'
    depends_on:
      - mongodb
    networks:
      - mynetwork

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    networks:
      - mynetwork

networks:
  mynetwork:
